image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: >
      python3 -m pip install -r requirements.txt

    command: >
      flask run -p 3000

vscode:
  extensions:
    - almenon.arepl@1.0.24:THeIDPSOMSJraJy4ii2Nlg==
