ports:
- port: 3000

tasks:
- init: > 
    python3 -m pip install -r requirements.txt 
  command: >
    export FLASK_APP=src/flask_app &&
    export FLASK_ENV=development &&
    flask run -p 3000

vscode:
  extensions:
    - almenon.arepl@1.0.24:THeIDPSOMSJraJy4ii2Nlg==