tasks:
  - init: pip3 install -r ./requirements.txt 
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - almenon.arepl@1.0.24:THeIDPSOMSJraJy4ii2Nlg==
    - littlefoxteam.vscode-python-test-adapter@0.4.5:AjFDI5oxInml/vtCNspL6w==