ports:
- port: 3000
  onOpen: open-preview

tasks:
- init: > 
    python3 -m pip install -r requirements.txt

  command: >
    gp env FLASK_APP=entrypoints/flask_app &&
    gp env FLASK_ENV=development &&
    gp env API_HOST=$(gp url 3000) &&
    eval $(gp env -e) &&
    flask run -p 3000
  

vscode:
  extensions:
    - almenon.arepl@1.0.24:THeIDPSOMSJraJy4ii2Nlg==